#!/bin/sh

cat <<BANNER
----------------------------------------------------------------------

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License Version 3 for more details.

You can ask questions, file a bug or make PRs here:
* https://github.com/QSCTech/zjunet

----------------------------------------------------------------------
BANNER

